name: Data Engineering CI/CD 101 Pipeline

on: push

jobs:
    etl-pipeline:
        runs-on: ubuntu-latest

        steps:


            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: Install Dependencies
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
            - name: Run ETL Pipeline
              run: |
                source venv/bin/activate
                python src/etl.py





            

 








    

 

